CREATE TABLE IF NOT EXISTS t_p72635010_quantum_fusion_resea.wip_builds (
    id SERIAL PRIMARY KEY,
    order_number VARCHAR(32) NOT NULL,
    stage VARCHAR(64) NOT NULL DEFAULT 'Согласование',
    contact VARCHAR(128),
    delivery_type VARCHAR(64),
    delivery_address VARCHAR(256),
    received_at DATE,
    issued_at DATE,
    comment TEXT,
    cpu VARCHAR(256),
    motherboard VARCHAR(256),
    ram VARCHAR(256),
    gpu VARCHAR(256),
    storage VARCHAR(256),
    psu VARCHAR(256),
    case_name VARCHAR(256),
    cooling VARCHAR(256),
    extra VARCHAR(512),
    cpu_status VARCHAR(32) DEFAULT 'pending',
    motherboard_status VARCHAR(32) DEFAULT 'pending',
    ram_status VARCHAR(32) DEFAULT 'pending',
    gpu_status VARCHAR(32) DEFAULT 'pending',
    storage_status VARCHAR(32) DEFAULT 'pending',
    psu_status VARCHAR(32) DEFAULT 'pending',
    case_status VARCHAR(32) DEFAULT 'pending',
    cooling_status VARCHAR(32) DEFAULT 'pending',
    extra_status VARCHAR(32) DEFAULT 'pending',
    order_id INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);