ALTER TABLE t_p72635010_quantum_fusion_resea.users
  ADD COLUMN IF NOT EXISTS user_tag VARCHAR(32) UNIQUE,
  ADD COLUMN IF NOT EXISTS is_public BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS avatar_url TEXT,
  ADD COLUMN IF NOT EXISTS telegram_tag VARCHAR(64);